Added check to the todo item
VICTOR-CHUKWU/Todo-List-microverse pull request #3
Opened 2021-09-29 21:11 UTC by VICTOR-CHUKWU

I added a check to the todo item

2021-09-29 22:30 UTC, carlos-ssh requested changes
Hi @VICTOR-CHUKWU , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-29 22:30 UTC, carlos-ssh commented on src/checked.js
> +      // alert(taskIndex);
- Kindly remove commented code.

2021-09-29 22:30 UTC, carlos-ssh commented on src/checked.js
> +        console.log(checkBoxes[i], 'mm');
- Kindly Remove console.logs

2021-09-30 09:10 UTC, wandji20 approved these changes
## Hi @VICTOR-CHUKWU  :raised_hands:

##### You have done exceptionally well, and have met all requirements for this project :+1:

# Status: Approved 👍 :partying_face: 

Your project has been approved, however, Keep up the good work.

## Congratulations :+1:  :fireworks: 
## Optional
- [ optional ] It will be nice to ignore all files that are not relevant to run this project(eg .lintrc, .stylelintrc.json, .eslintrc.json etc).

_Go ahead and merge this branch. Also, don't forget to submit the project completion form.
Good luck with your next project :mechanical_arm:  :slightly_smiling_face:_ 

 If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-30 09:22 UTC, merged